import React from 'react';
import App from '../App';

function Earthquake() {
    return (
        <>
            <App current="Prepare" cS="Earthquake" />
            <div className='h-screen relative -top-20 '>
                <img alt="" src={process.env.PUBLIC_URL + '/bgEarthquake.jpg'} className='w-full object-cover relative h-full block' />
                <div className='h-full w-full bg-gradient-to-r from-slate-900 absolute top-0 block'></div>
                <div className="absolute top-0 flex flex-col justify-center mx-5 lg:mx-28 h-full space-y-6 font-semibold font-sora ">
                    <h1 className='text-2xl sm:text-3xl md:text-6xl text-smartblue'>Earthquake</h1>
                    <div className='flex flex-col md:flex-row md:space-x-5 space-y-5 md:space-y-0 text-center'>
                        <a href='#short-read' className='transition ease-in-out w-48 duration-300 bg-smartblue font-nunito font-semibold text-white md:px-6 md:py-3 rounded-lg hover:bg-orange-600 xsm:px-4 xsm:py-2 px-2 py-1 cursor-pointer'>Short Read</a>
                        <a href='#long-read' className='transition ease-in-out w-48 duration-300 bg-smartblue font-nunito font-semibold text-white md:px-6 md:py-3 rounded-lg hover:bg-orange-600 xsm:px-4 xsm:py-2 px-2 py-1 cursor-pointer'>Long Read</a>
                    </div>
                </div>
            </div>
            <div className='space-y-9'>
                <div className='space-y-10 mt-10 mb-24' id='short-read'>
                    <h1 className='font-sora text-4xl md:text-7xl text-slate-900 mx-5 sm:mx-10 md:mx-16 lg:mx-24'>Short Read</h1>
                    <p className='text-sm sm:text-xl md:text-2xl text-slate-900  mx-5 sm:mx-10 md:mx-16 lg:mx-24 font-nunito'>
                        Any sudden shaking of the ground generated by seismic waves passing through Earth's rocks is referred to as an Earthquake. Foreshocks are lesser earthquakes that occur in the same location as the following big earthquake. The mainshock is the greatest and most powerful earthquake. Aftershocks are lesser earthquakes that strike near the epicenter of the mainshock.
                    </p>
                    <ul role="list" className="marker:text-sky-400 list-disc pl-5 text-sm sm:text-xl md:text-2xl space-y-3 text-slate-900 mx-5 sm:mx-10 md:mx-16 lg:mx-24 font-semibold">
                        <li><span className='underline decoration-sky-400'>Preparing for an Earthquake:</span> It is critical to recognize potential hazards ahead of time. After earthquake you may not have access to basic essentials and hence should create a disaster supply kit. Developing an emergency communication plan is also essential for the aftermath.</li>
                        <li><span className='underline decoration-sky-400'>Staying Safe During an Earthquake:</span> Learn where the safe zones are in each of your home's rooms. Do not run outside or to other rooms. Hold on to a possible shelter over your head and neck until the shaking stops.</li>
                        <li><span className='underline decoration-sky-400'>Staying Safe After an Earthquake:</span> Smaller earthquakes that occur after a major earthquake are known as aftershocks. Follow the same procedures for remaining safe during earthquake. If you're stuck, try to draw attention to yourself. It is important to cope with emotions and seeking assistance after an earthquake.</li>
                    </ul>
                </div>
                <div className='space-y-10 mt-10 pb-16' id='long-read'>
                    <h1 className='font-sora text-4xl md:text-7xl text-slate-900 mx-5 sm:mx-10 md:mx-16 lg:mx-24 '>Long Read</h1>
                    <p className='text-sm sm:text-xl md:text-2xl text-slate-900  mx-5 sm:mx-10 md:mx-16 lg:mx-24 font-nunito'>
                        Any sudden shaking of the ground generated by seismic waves passing through Earth's rocks is referred to as an Earthquake. Seismic waves are created when energy held in the Earth's crust is released suddenly, usually when masses of rock straining against one another crack and slip. Geologic faults, narrow zones where rock masses move in relation to one another, are the most common locations for earthquakes. The world's primary fault lines run along the edges of the massive tectonic plates that make up the Earth's crust. Foreshocks can occur during an earthquake. These are lesser earthquakes that occur in the same location as the following big earthquake. Scientists can't identify if an earthquake is a foreshock until the main event occurs. The mainshock is the greatest and most powerful earthquake. Mainshocks are always followed by aftershocks. These are lesser earthquakes that strike near the epicenter of the mainshock. Aftershocks can last for weeks, months, or even years after the mainshock, depending on the size of the mainshock.
                    </p>
                    <ul role="list" className="marker:text-sky-400 list-disc pl-5 text-sm sm:text-xl md:text-2xl space-y-3 text-slate-900 mx-5 sm:mx-10 md:mx-16 lg:mx-24 font-semibold">
                        <li>
                            <span className='font-semibold underline text-smartblue decoration-smartblue'>Preparing for an Earthquake:</span> It is critical to recognize potential hazards ahead of time, as well as to plan ahead of time to limit the risk of significant injury or death as a result of an earthquake. Identifying potential hazards before an earthquake might help you and others stay safe. To ensure that objects do not fall forcefully during an earthquake, take an inventory of your home or place of business. After an earthquake, you may not have access to water, food, electricity, or other requirements, so you should prepare a disaster supply kit with extra water, food, and other essentials. Because we cannot rely on cell phones or other gadgets that require electricity after an earthquake, developing an emergency communication plan can be beneficial.
                        </li>
                        <li>
                            <span className='font-semibold underline text-smartblue decoration-smartblue'>Staying Safe During an Earthquake:</span> Collapsing materials and large falling objects, such as bookcases and cabinets, cause the majority of deaths and injuries during an earthquake. Learn where the safe zones are in each of your home's rooms. If you're already in bed, a secure position could be underneath a sturdy table away from walls or below the covers with a pillow over your head. During an earthquake, do not run outside or to other rooms. If you stay put, you have a lower chance of getting hurt. Hold on to a possible shelter over your head and neck until the shaking stops. If the shaking causes your shelter to shift, be ready to move with it.
                        </li>
                        <li>
                            <span className='font-semibold underline text-smartblue decoration-smartblue'>Staying Safe After an Earthquake:</span> Aftershocks may occur following an earthquake. Smaller earthquakes that occur after a major earthquake are known as aftershocks. If this occurs, follow the same procedures for remaining safe during an earthquake. If you're stuck, try to draw attention to yourself. To assist rescuers in finding you, send a message by pounding on a wall or a pipe, or blowing a whistle. During and after an earthquake, there is a substantial danger of harm. Get first aid as soon as possible to aid in the healing of tiny wounds and the prevention of infection. It is typical to feel a variety of powerful emotions during and after an earthquake. Coping with these emotions and seeking assistance when needed will aid you, your family, and your community in recovering after a tragedy.
                        </li>
                    </ul>
                </div>
                <div className='bg-white p-4 text-center text-xl font-nunito font-semibold text-slate-900'>
                    <h1>&copy; Copyright 2022 MetaAid</h1>
                </div>
            </div>
        </>
    );
}

export default Earthquake;
